### ISSUE TITLE
group service bad mapped in namespace

### ISSUE THREAD

**Issue by mckaygerhard** [CNRS-DSI-Dev/dashboard#17] opened 2015-03-12 19:42 UTC
the namespace mapped in groupservice are in lowercase, must be in Case-sensitive for app god work, some error are due that! in guindows like this are not problem , but in real os this make app dont work very well..

**Comment by ppaysant** [comment] 2017-03-02 16:05
Can't reproduce. This app is used in production for 2 years on a redhat server, I developp on debian or centos and everything works fine.
I close the issue

**Closed by ppaysant** 2017-03-02 16:05 UTC

**Comment by mckaygerhard** [comment] 2017-03-06 20:29
okey i dont understant that:

the namesapace and use are like:

`namespace OCA\Dashboard` and use `use OCA\Dashboard`

but in https://github.com/CNRS-DSI-Dev/dashboard/blob/master/appinfo/app.php#L35 i can see not same, using `'\OCA\dashboard\`

some other files are same, this are right or i dont understnd the oc code?

**Comment by ppaysant** [comment] 2017-03-07 09:31
Don't mix namespace and directories, even if it's linked. It seems (I mean "I observe in production") that namespaces case is not a problem here.

regards
